apiVersion: v1
kind: Service
metadata:
  name: habits-tracker-service
spec:
  selector:
    app: habits-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080  
  type: NodePort
